# Site settings
title: CS10
email: info@cs10.org
# Note the weird ' > # ' syntax is for multiline stuff
description: > # CS10, The Beauty and Joy of Computing, is an introductory
    computer science class designed for anyone and everyone. The Beauty and
    Joy of Computing is an AP Computer Science Principles class.
keywords: "CS10, UC, Berkeley, CS, computer science, BJC, computing, education, Snap!, CS Principles, AP"
baseurl: ""
url: "https://cs10.org"

# Build settings
markdown: kramdown


# CSS Style
sass:
    style: :compressed
    sass_dir: assets/_sass

plugins:
  - jekyll-sitemap

# TODO: TA Collections
# collections:
    # - tas:
        # output: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - includes
  - update-index.sh
